name: CI/CD Pipeline

on:
  push:
    branches: [ '**' ]
    tags: [ '**' ]  # Trigger on tag creation

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.10'

    - name: Run unit tests
      run: |
        docker build . --target tester

    - name: Login to Docker Hub
      if: startsWith(github.ref, 'refs/tags/') # Only login for tag pushes
      uses: docker/login-action@v1
      with:
        username: ${{ secrets.DOCKER_HUB_USERNAME }}
        password: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}

    - name: Build and push Docker image to Docker Hub
      if: startsWith(github.ref, 'refs/tags/') # Only push for tag pushes
      run: |
        TAG=${GITHUB_REF#refs/tags/}
        IMAGE_NAME=${{ secrets.DOCKER_HUB_USERNAME }}/prop-puller:$TAG
        docker build . --tag $IMAGE_NAME --target production
        docker push $IMAGE_NAME

    - name: Logout of Docker Hub
      if: startsWith(github.ref, 'refs/tags/') # Only logout for tag pushes
      run: docker logout
